default: &default
  adapter: postgresql
  encoding: unicode
  # Connection pool settings - optimized for efficiency
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  checkout_timeout: 3
  reaping_frequency: 30
  idle_timeout: 60
  # Disable prepared statements to reduce connection overhead
  prepared_statements: false
  # Configure timeouts for queries
  variables:
    statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 30000) %>  # 30 seconds
    lock_timeout: <%= ENV.fetch("LOCK_TIMEOUT", 5000) %>  # 5 seconds
    idle_in_transaction_session_timeout: <%= ENV.fetch("IDLE_TRANSACTION_TIMEOUT", 60000) %>  # 1 minute
  # Connection validation
  reconnect: true
  connect_timeout: 2

development:
  <<: *default
  database: ptex_development
  # Use localhost for TCP/IP connection
  host: localhost
  # Smaller pool for development to prevent exhaustion
  pool: 2
  checkout_timeout: 1

test:
  <<: *default
  database: ptex_test
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  <<: *default
  database: ptex_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
